### ISSUE TITLE
Use parameters properly

### ISSUE THREAD

**Issue by lucasw** [lucasw/image_manip#13]
Currently using parameter_events, but this looks to not be the right tool- all the nodes in the same namespace share this topic.

Look at register_param_change_callback instead.

**Comment by lucasw** [comment]
It looks like that if parameters don't need to be validated then calling get_parameter variants is the way to access them.

**Comment by lucasw** [comment]
The right way to access parameters is to call get_parameter_or()?  Still probably want to cache the values if using in a loop.

The callback is still useful for detecting changes, a dirty bool could be set.

**Comment by lucasw** [comment]
With gen_color and imgui_ros running with imgui_ros having a parameter client to change gen_color parameters:

```
ros2 param set gen_color blue 42
```
```
stamp:
  sec: 1547131150
  nanosec: 267429120
node: /_ros2cli_node_23009
new_parameters: []
changed_parameters: []
deleted_parameters: []

stamp:
  sec: 1547131150
  nanosec: 774887804
node: /gen_color
new_parameters: []
changed_parameters:
- name: blue
  value:
    type: 2
    bool_value: false
    integer_value: 42
    double_value: 0.0
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
deleted_parameters: []
```

So the source of some confusion is that there are two parameter events, one does have the proper parameter and the target node name, the other is blank and for what use?
